part of 'main.dart';

const List<EsaTeknikKonu> esaDerinKorumaOlcum = [
  EsaTeknikKonu(
    id: 'ct-0-5s',
    kategori: 'Ölçü & Koruma',
    baslik: 'CT 0,5S doğruluk sınıfı',
    ozet: '0,5S bir akım trafosunun ölçü doğruluğu sınıfını ifade eder; özellikle düşük akımlarda ölçüm performansının değerlendirilmesinde önemlidir.',
    nedir: '0,5S, IEC 61869-2 kapsamında ölçü akım trafoları için kullanılan doğruluk sınıflarından biridir. S sınıfları düşük primer akım bölgesindeki ölçüm davranışını ayrıca ele alır.',
    nasil: 'CT seçilirken yalnızca 10/5 veya 100/5 gibi oran değil; doğruluk sınıfı, frekans, burden ve kullanım amacı birlikte değerlendirilir. Kesin hata limitleri ilgili standardın şartlarından alınmalıdır.',
    saha: 'Enerji ölçümü ve sayaç uygulamalarında düşük yüklerde de kabul edilebilir ölçüm doğruluğu gerektiğinde 0,5S gibi sınıflar gündeme gelebilir.',
    dikkat: '0,5S ifadesi tek başına tüm ölçüm doğruluğunu garanti etmez. CT oranı, burden, cihaz girişi ve gerçek çalışma koşulları birlikte doğrulanmalıdır.',
    ilgiliAraclar: 'Ölçü Trafo, OG Hücre, Pano Malzeme Seçimi',
    kaynak: 'IEC 61869-2:2012 ve ilgili güncel ulusal uygulamalar',
  ),
  EsaTeknikKonu(
    id: 'ct-burden',
    kategori: 'Ölçü & Koruma',
    baslik: 'CT burden',
    ozet: 'Akım trafosunun sekonderine bağlı ölçü ve koruma devresinin oluşturduğu yükü ifade eder.',
    nedir: 'Burden, CT sekonder devresinin CT açısından oluşturduğu elektriksel yüktür. Kablo direnci, ölçü cihazı/röle girişi ve bağlantılar toplam davranışa katkı verir.',
    nasil: 'CT oranı ve sınıfı belirlenirken sekonder kablo uzunluğu, kesiti, cihazların giriş yükleri ve bağlantı noktaları dikkate alınır.',
    saha: 'Uzun CT sekonder kablolarında kablo direnci artacağından burden hesabı önem kazanır.',
    dikkat: 'Sadece sayaç girişindeki VA değerine bakmak yeterli değildir; sekonder kablolama da hesaba dahil edilmelidir.',
    ilgiliAraclar: 'Ölçü Trafo, OG Hücre',
    kaynak: 'IEC 61869-2; üretici CT katalogları',
  ),
  EsaTeknikKonu(
    id: 'ct-saturation',
    kategori: 'Ölçü & Koruma',
    baslik: 'CT doyumu',
    ozet: 'Akım trafosunun manyetik çekirdeğinin doğrusal çalışma bölgesinden çıkmasıdır.',
    nedir: 'Primer akım arttığında sekonder akım artık ideal oranı takip etmeyebilir. Bu durum ölçü veya koruma fonksiyonunu etkileyebilir.',
    nasil: 'CT çekirdeği, oranı, sınıfı, burden ve arıza akımı birlikte değerlendirilir. Koruma CTlerinde geçici rejim davranışı ayrıca önemlidir.',
    saha: 'Kısa devre sırasında koruma rölesinin beklenen akımı görememesi yanlış açma veya açmama riskini doğurabilir.',
    dikkat: 'Koruma CTsi ile ölçü CTsinin amacı aynı değildir; sınıf ve transient davranış buna göre seçilir.',
    ilgiliAraclar: 'OG Hücre, Ölçü Trafo',
    kaynak: 'IEC 61869-2; üretici koruma CT verileri',
  ),
  EsaTeknikKonu(
    id: 'idyn',
    kategori: 'Pano & Kısa Devre',
    baslik: 'Idyn / dinamik dayanım akımı',
    ozet: 'Kısa devrenin oluşturduğu elektromekanik kuvvetlere karşı ekipmanın dayanımının değerlendirilmesinde kullanılan tepe akım büyüklüğüdür.',
    nedir: 'Kısa devre yalnızca iletkenleri ısıtmaz; çok büyük anlık elektromekanik kuvvetler de oluşturur. Dinamik dayanım bu etkiye karşı mekanik yeterliliği ifade eder.',
    nasil: 'Ekipmanın kısa devre testleri ve ilgili standarttaki dayanım değerleri kullanılır. Kısa devrenin ilk tepe akımı, sistemin X/R oranı ve ekipmanın yapısı önemlidir.',
    saha: 'Bara destekleri, bağlantılar ve şalt ekipmanının kısa devre anındaki mekanik davranışı açısından kritiktir.',
    dikkat: 'Dinamik dayanım ile kısa süreli termik dayanım aynı kavram değildir.',
    ilgiliAraclar: 'Pano Malzeme Seçimi, Kısa Devre',
    kaynak: 'IEC 61439 serisi; IEC 62271 serisi',
  ),
  EsaTeknikKonu(
    id: 'icw',
    kategori: 'Pano & Kısa Devre',
    baslik: 'Icw / kısa süre dayanım akımı',
    ozet: 'Pano veya şalt ekipmanının belirli bir süre boyunca dayanabildiği kısa devre akımını ifade eder.',
    nedir: 'Icw, ekipmanın belirlenmiş süre boyunca kısa devrenin termik ve elektromekanik etkilerine dayanma kapasitesinin bir parçasıdır.',
    nasil: 'Hesaplanan kısa devre akımı, ekipmanın Icw değeri ve belirtilen dayanım süresiyle karşılaştırılır.',
    saha: 'Kesici açmadan önce kısa devre akımının pano üzerinde oluşturacağı etkiyi değerlendirmede önemlidir.',
    dikkat: 'Icw ile kesicinin kısa devre kesme kapasitesi aynı parametre değildir.',
    ilgiliAraclar: 'Pano Malzeme Seçimi, Kısa Devre',
    kaynak: 'IEC 61439-1:2020; üretici doğrulama verileri',
  ),
  EsaTeknikKonu(
    id: 'ipk',
    kategori: 'Pano & Kısa Devre',
    baslik: 'Ipk / tepe dayanım akımı',
    ozet: 'Pano veya ekipmanın kısa devre sırasında dayanabildiği tepe akımını ifade eder.',
    nedir: 'Kısa devrenin ilk anındaki asimetrik tepe akımı, ekipmanda çok yüksek elektromekanik kuvvetler oluşturabilir.',
    nasil: 'Prospektif kısa devre akımı ve sistemin kısa devre karakteriyle ilişkilendirilerek ekipmanın Ipk değeriyle karşılaştırılır.',
    saha: 'Bara ve bağlantı mekanik dayanımı açısından özellikle önemlidir.',
    dikkat: 'Ipk, RMS kısa devre akımı değildir; tepe değerdir.',
    ilgiliAraclar: 'Pano Malzeme Seçimi, Kısa Devre',
    kaynak: 'IEC 61439-1:2020; üretici verileri',
  ),
  EsaTeknikKonu(
    id: 'short-circuit',
    kategori: 'Kısa Devre',
    baslik: 'Kısa devre akımı',
    ozet: 'Arıza noktası empedansının çok düşmesiyle oluşan yüksek arıza akımıdır.',
    nedir: 'Faz-faz, faz-toprak veya diğer arıza tiplerinde kaynak ve iletken empedanslarının belirlediği yüksek akımdır.',
    nasil: 'Kaynak gücü, trafo empedansı, kablo empedansı ve arıza tipine göre hesaplanır.',
    saha: 'Kesici kesme kapasitesi, pano dayanımı ve koruma ayarlarının temel girdilerindendir.',
    dikkat: 'En yüksek kısa devre akımı ile en düşük arıza akımı farklı amaçlarla incelenebilir.',
    ilgiliAraclar: 'Kısa Devre, Pano, Sigorta',
    kaynak: 'IEC 60909 serisi; ilgili tesis standartları',
  ),
];
