part of 'main.dart';

const List<EsaTeknikKonu> esaDerinKablo = [
  EsaTeknikKonu(
    id: 'cable-correction',
    kategori: 'Kablo & Hatlar',
    baslik: 'Düzeltme katsayıları',
    ozet: 'Referans kablo kapasitesinin gerçek tesis koşullarına uyarlanmasını sağlayan katsayılardır.',
    nedir: 'Ortam sıcaklığı, gruplanma, döşeme şekli, toprak termik özellikleri gibi etkenler kablonun ısı atmasını değiştirir.',
    nasil: 'Önce referans döşeme yöntemi belirlenir; ardından ilgili standardın veya üreticinin düzeltme katsayıları uygulanır.',
    saha: 'Aynı kesit kablolar yan yana sıkıştırıldığında veya sıcak ortamda çalıştığında kapasite düşebilir.',
    dikkat: 'Katsayılar gelişigüzel seçilmemeli; kablo tipi ve döşeme yöntemiyle uyumlu tablodan alınmalıdır.',
    ilgiliAraclar: 'Kablo Kapasitesi, Hat Analizi',
    kaynak: 'IEC 60364-5-52; üretici kablo tabloları',
  ),
  EsaTeknikKonu(
    id: 'cable-grouping',
    kategori: 'Kablo & Hatlar',
    baslik: 'Kablo gruplanması',
    ozet: 'Birden fazla yüklü devrenin birbirine yakın döşenmesinin kapasite üzerindeki etkisidir.',
    nedir: 'Yakındaki kablolar birbirlerinin ısıl ortamını artırarak ısı atımını zorlaştırabilir.',
    nasil: 'Devre sayısı, kablo düzeni, aralık ve döşeme biçimine göre ilgili düzeltme katsayısı belirlenir.',
    saha: 'Tava ve borularda kablo sayısı arttıkça kapasite kontrolü önem kazanır.',
    dikkat: 'Kablo adedini yalnızca fiziksel sığma açısından değil, termik açıdan da değerlendirin.',
    ilgiliAraclar: 'Boru/Tava Doluluk, Kablo Kapasitesi',
    kaynak: 'IEC 60364-5-52; üretici verileri',
  ),
  EsaTeknikKonu(
    id: 'cable-voltage-drop',
    kategori: 'Kablo & Hatlar',
    baslik: 'Gerilim düşümünde cosφ etkisi',
    ozet: 'AC hatlarda kablo direnci yanında reaktans ve güç faktörü de gerilim düşümünü etkiler.',
    nedir: 'Akım ile kablo empedansının etkileşimi sonucu yük ucunda gerilim azalır.',
    nasil: 'Kablo direnç ve reaktans bileşenleri, akım, uzunluk ve cosφ ile birlikte değerlendirilir.',
    saha: 'Motor ve uzun hatlarda cosφ değişimi gerilim düşümü sonucunu etkileyebilir.',
    dikkat: 'Sadece R x I yaklaşımı her AC hat için yeterli olmayabilir.',
    ilgiliAraclar: 'Hat Analizi, Gerilim Düşümü',
    kaynak: 'IEC 60364-5-52 ve ilgili kablo verileri',
  ),
  EsaTeknikKonu(
    id: 'cable-short-circuit',
    kategori: 'Kablo & Hatlar',
    baslik: 'Kablonun kısa devre termik dayanımı',
    ozet: 'Kablonun kısa devre süresince iletken sıcaklığının izin verilen sınırlar içinde kalmasıdır.',
    nedir: 'Kısa devre akımı çok kısa sürede büyük ısı üretir. Kablo iletkeni ve yalıtımı belirli sıcaklık sınırlarına sahiptir.',
    nasil: 'Kısa devre akımı, açma süresi, iletken malzemesi ve başlangıç/son sıcaklık sınırları birlikte değerlendirilir.',
    saha: 'Koruma cihazının açma süresi uzadığında kablonun kısa devre dayanımı kritik hale gelir.',
    dikkat: 'Kısa devre termik dayanımı ile sürekli akım taşıma kapasitesi farklı kontrollerdir.',
    ilgiliAraclar: 'Kısa Devre, Kablo ve Sigorta',
    kaynak: 'IEC 60364 serisi; ilgili kablo ürün standardı',
  ),
];
