part of 'main.dart';

const List<EsaTeknikKonu> esaDerinGes = [
  EsaTeknikKonu(
    id: 'pv-cold-voc',
    kategori: 'GES / Solar',
    baslik: 'Soğukta Voc kontrolü',
    ozet: 'PV stringinin açık devre geriliminin düşük sıcaklıkta artması nedeniyle yapılan maksimum DC gerilim kontrolüdür.',
    nedir: 'PV hücre gerilimi sıcaklıkla değişir. Düşük sıcaklıkta Voc artabildiği için string toplam Voc inverterin maksimum DC giriş gerilimini aşmamalıdır.',
    nasil: 'Modül datasheetindeki sıcaklık katsayısı ve tasarım minimum sıcaklığı kullanılarak string Voc kontrol edilir.',
    saha: 'Özellikle soğuk iklimlerde seri modül sayısı belirlenirken bu kontrol kritik olabilir.',
    dikkat: 'Sadece STC Voc ile string seçmek güvenli maksimum gerilim kontrolü için yeterli değildir.',
    ilgiliAraclar: 'GES String Tasarımı, GES İnverter Analizi',
    kaynak: 'IEC 62548-1:2023+AMD1:2025; üretici PV datasheet',
  ),
  EsaTeknikKonu(
    id: 'pv-mppt-window',
    kategori: 'GES / Solar',
    baslik: 'MPPT çalışma aralığı',
    ozet: 'Stringin çalışma geriliminin inverterin MPPT gerilim aralığında kalmasıdır.',
    nedir: 'İnverterin MPPT devresi belirli bir DC gerilim aralığında maksimum güç noktasını takip eder.',
    nasil: 'String Vmp sıcaklık aralığı boyunca MPPT minimum ve maksimum sınırlarıyla karşılaştırılır.',
    saha: 'Aşırı uzun veya kısa stringlerde inverter verimli MPPT bölgesinde çalışamayabilir.',
    dikkat: 'MPPT çalışma aralığı ile maksimum DC giriş gerilimi aynı sınır değildir.',
    ilgiliAraclar: 'GES String, GES İnverter',
    kaynak: 'IEC 62548-1:2023+AMD1:2025; üretici inverter datasheet',
  ),
  EsaTeknikKonu(
    id: 'pv-parallel-current',
    kategori: 'GES / Solar',
    baslik: 'Paralel string akımı',
    ozet: 'Aynı girişe paralel bağlanan stringlerin toplam akım etkisidir.',
    nedir: 'Seri stringde gerilim artarken paralel stringlerde akım toplanır.',
    nasil: 'String Imp/Isc değerleri ve paralel string sayısı inverter MPPT giriş akım sınırıyla karşılaştırılır.',
    saha: 'Çoklu string tasarımında MPPT giriş akımı kritik bir sınırdır.',
    dikkat: 'Sadece toplam kWp değerine bakmak inverter giriş akımını garanti etmez.',
    ilgiliAraclar: 'GES String, GES İnverter',
    kaynak: 'IEC 62548-1:2023+AMD1:2025; üretici inverter datasheet',
  ),
  EsaTeknikKonu(
    id: 'pv-60vdc',
    kategori: 'GES / Solar',
    baslik: 'Düşük DC gerilimli sistemler',
    ozet: '60 VDC seviyesinden başlayan küçük ölçekli PV, karavan ve batarya sistemlerinde DC tasarım yaklaşımıdır.',
    nedir: 'Düşük DC gerilimli sistemlerde aynı güç için akım yükselir. Bu nedenle kablo kesiti ve kayıplar önem kazanır.',
    nasil: 'Sistem gerilimi, yük gücü, kablo uzunluğu ve izin verilen DC gerilim düşümü birlikte değerlendirilir.',
    saha: 'Karavan ve küçük bağımsız sistemlerde 12/24/48/60 V sınıfı çözümlerle karşılaşılabilir.',
    dikkat: 'Düşük gerilim güvenli kabul edilse bile yüksek akım; ısınma, sigorta ve kablo kesiti açısından ciddi risk oluşturabilir.',
    ilgiliAraclar: 'GES Karavan, GES Sistem',
    kaynak: 'İlgili DC tesis kuralları; üretici ekipman verileri',
  ),
  EsaTeknikKonu(
    id: 'pump-hmt',
    kategori: 'GES Tarımsal',
    baslik: 'HMT / toplam basma yüksekliği',
    ozet: 'Pompanın debiyi istenen noktaya ulaştırmak için yenmesi gereken toplam enerji yüksekliğidir.',
    nedir: 'Statik yükseklik, boru sürtünme kayıpları ve yerel kayıplar gibi bileşenlerin toplam etkisini temsil eder.',
    nasil: 'Debi ihtiyacı ile birlikte boru uzunluğu, çapı, kot farkı, vana/dirsek kayıpları ve çıkış koşulları değerlendirilir.',
    saha: 'Pompa seçimi sadece motor kW değerinden yapılmamalıdır; gerçek çalışma noktası Q-H eğrisi üzerinde kontrol edilir.',
    dikkat: 'HMT ile yalnızca kot farkını eşitlemek sürtünme kayıplarını ihmal eder.',
    ilgiliAraclar: 'GES Tarımsal Sistem Tasarımı',
    kaynak: 'Pompa üreticisi Q-H eğrileri; ilgili hidrolik tasarım verileri',
  ),
];
