part of 'main.dart';

const List<EsaTeknikKonu> esaGesBilgileri = [
  EsaTeknikKonu(
    id: 'vmp',
    kategori: 'GES / Solar',
    baslik: 'Vmp',
    ozet: 'PV modülünün maksimum güç noktasındaki gerilimidir.',
    nedir: 'Çalışma noktasındaki PV gerilimidir.',
    nasil: 'Seri modüllerde gerilimler toplanır.',
    saha: 'String Vmp, inverter MPPT aralığıyla karşılaştırılır.',
    dikkat: 'Sıcaklıkla değişir; sabit şebeke gerilimi değildir.',
    ilgiliAraclar: 'GES String',
    kaynak: 'IEC 62548-1:2023+AMD1:2025; üretici datasheet',
  ),
  EsaTeknikKonu(
    id: 'voc',
    kategori: 'GES / Solar',
    baslik: 'Voc',
    ozet: 'PV modülünün açık devre gerilimidir.',
    nedir: 'Akım çekilmezken oluşan gerilimdir.',
    nasil: 'String Voc, inverter maksimum DC gerilimiyle karşılaştırılır.',
    saha: 'Soğuk koşullarda artış dikkate alınır.',
    dikkat: 'Vmp ile Voc karıştırılmamalıdır.',
    ilgiliAraclar: 'GES String, İnverter',
    kaynak: 'IEC 62548-1:2023+AMD1:2025; üretici datasheet',
  ),
  EsaTeknikKonu(
    id: 'mppt',
    kategori: 'GES / Solar',
    baslik: 'MPPT',
    ozet: 'Maksimum güç noktası izleme kontrolüdür.',
    nedir: 'PV dizisinin uygun çalışma noktasından güç çekmeyi amaçlar.',
    nasil:
        'String gerilimi MPPT aralığında ve akım/gerilim sınırları içinde tutulur.',
    saha:
        'Yanlış stringleme verimi düşürebilir veya cihaz sınırlarını aşabilir.',
    dikkat: 'MPPT sayısı ve her MPPT’nin akım sınırı ayrıca kontrol edilir.',
    ilgiliAraclar: 'GES Sistem, String, Karavan',
    kaynak: 'IEC 62548-1:2023+AMD1:2025',
  ),
  EsaTeknikKonu(
    id: 'isc-imp',
    kategori: 'GES / Solar',
    baslik: 'Isc / Imp',
    ozet: 'Isc kısa devre; Imp maksimum güç noktası akımıdır.',
    nedir: 'İki farklı PV akım parametresidir.',
    nasil: 'Paralel stringlerde akımlar toplanır.',
    saha: 'İnverter giriş akım sınırıyla karşılaştırılır.',
    dikkat: 'Isc ve Imp aynı değer değildir.',
    ilgiliAraclar: 'GES String, İnverter',
    kaynak: 'IEC 62548-1:2023+AMD1:2025; üretici datasheet',
  ),
  EsaTeknikKonu(
    id: 'string',
    kategori: 'GES / Solar',
    baslik: 'PV string',
    ozet: 'Seri bağlanmış PV modüllerinin dizisidir.',
    nedir: 'Seri bağlantı gerilimi, paralel bağlantı toplam akımı artırır.',
    nasil: 'String gerilimi ve akımı cihaz sınırlarıyla kontrol edilir.',
    saha: 'Aynı MPPT’ye bağlanan stringler uyumlu olmalıdır.',
    dikkat: 'Sadece kWp toplamına bakarak stringleme yapılmaz.',
    ilgiliAraclar: 'GES String',
    kaynak: 'IEC 62548-1:2023+AMD1:2025',
  ),
];
