part of 'main.dart';

const List<EsaTeknikSozlukMaddesi> esaTeknikSozluk = [
  EsaTeknikSozlukMaddesi(
    terim: "AC",
    acilim: "Alternatif akım",
    tanim: "Yönü ve değeri zamanla değişen akımdır.",
    saha: "Şebeke ve motor sistemlerinde temel akım türüdür.",
    ilgili: "AG, Motor",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "DC",
    acilim: "Doğru akım",
    tanim: "Yönü sabit kabul edilen akımdır.",
    saha: "PV ve batarya sistemlerinin temel akım türüdür.",
    ilgili: "GES, Karavan",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "kW",
    acilim: "Kilowatt",
    tanim: "Aktif güç birimidir.",
    saha: "Motor ve yük gücünde kullanılır.",
    ilgili: "Motor, GES",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "kVA",
    acilim: "Kilovoltamper",
    tanim: "Görünür güç birimidir.",
    saha: "Trafo kapasitesinde yaygındır.",
    ilgili: "Trafo",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "kvar",
    acilim: "KilovAr",
    tanim: "Reaktif güç birimidir.",
    saha: "Kompanzasyon kademelerinde kullanılır.",
    ilgili: "Kompanzasyon",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "cosφ",
    acilim: "Güç faktörü",
    tanim: "Aktif gücün görünür güce oranıdır.",
    saha: "Akım hesaplarında ve kompanzasyonda kullanılır.",
    ilgili: "Kompanzasyon, Sigorta",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "MCB",
    acilim: "Minyatür devre kesici",
    tanim: "Son devrelerde aşırı akım koruması sağlar.",
    saha: "Pano ve son devrelerde kullanılır.",
    ilgili: "Koruma",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "MCCB",
    acilim: "Kompakt devre kesici",
    tanim: "Yüksek akım ve ayarlanabilir koruma uygulamalarında kullanılır.",
    saha: "Ana dağıtımda yaygındır.",
    ilgili: "Koruma",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "RCD",
    acilim: "Residual Current Device",
    tanim: "Artık ve kaçak akım koruma cihazı ailesidir.",
    saha: "Kaçak akım korumasında kullanılır.",
    ilgili: "Koruma",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "CT",
    acilim: "Current Transformer",
    tanim: "Akım trafosunun kısaltmasıdır.",
    saha: "Ölçü ve korumada kullanılır.",
    ilgili: "OG, Ölçü Trafo",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "VT",
    acilim: "Voltage Transformer",
    tanim: "Gerilim trafosunun kısaltmasıdır.",
    saha: "Ölçü ve korumada kullanılır.",
    ilgili: "OG",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "VFD",
    acilim: "Variable Frequency Drive",
    tanim: "Değişken frekanslı motor sürücüsüdür.",
    saha: "Motor hız kontrolünde kullanılır.",
    ilgili: "Motor",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "MPPT",
    acilim: "Maximum Power Point Tracking",
    tanim: "Maksimum güç noktası izleme kontrolüdür.",
    saha: "PV inverter ve şarj cihazlarında kullanılır.",
    ilgili: "GES",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "Vmp",
    acilim: "Maximum Power Voltage",
    tanim: "PV maksimum güç noktası gerilimidir.",
    saha: "String çalışma geriliminde kullanılır.",
    ilgili: "GES",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "Voc",
    acilim: "Open Circuit Voltage",
    tanim: "PV açık devre gerilimidir.",
    saha: "Maksimum DC gerilim kontrolünde kullanılır.",
    ilgili: "GES",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "Imp",
    acilim: "Maximum Power Current",
    tanim: "PV maksimum güç noktası akımıdır.",
    saha: "Paralel string akımında kullanılır.",
    ilgili: "GES",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "Isc",
    acilim: "Short Circuit Current",
    tanim: "PV kısa devre akımıdır.",
    saha: "Koruma ve giriş akımı değerlendirmesinde kullanılır.",
    ilgili: "GES",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "PE",
    acilim: "Protective Earth",
    tanim: "Koruma iletkenidir.",
    saha: "Arıza koruma yolunun parçasıdır.",
    ilgili: "Topraklama",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "PEN",
    acilim: "Protective Earth and Neutral",
    tanim: "Koruma ve nötr fonksiyonlarını birleştiren iletkendir.",
    saha: "Belirli TN sistemlerinde kullanılır.",
    ilgili: "Topraklama",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "TN-S",
    acilim: "TN-S",
    tanim: "PE ve N iletkenlerinin ayrı tutulduğu TN düzenidir.",
    saha: "Tesis dağıtımında ayrı PE ve N yapısı sağlar.",
    ilgili: "Topraklama",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "TT",
    acilim: "TT",
    tanim: "Kaynak ve tesis topraklamasının ayrı olduğu sistem ailesidir.",
    saha: "RCD ve topraklama ile birlikte değerlendirilir.",
    ilgili: "Topraklama",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "XLPE",
    acilim: "Çapraz bağlı polietilen",
    tanim: "Kablo yalıtım malzemesidir.",
    saha: "AG ve OG kablolarda kullanılır.",
    ilgili: "Kablo",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "NYY",
    acilim: "NYY",
    tanim: "Bakır iletkenli PVC yalıtımlı güç kablosu ailesidir.",
    saha: "Sabit tesislerde yaygındır.",
    ilgili: "Kablo",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "NAYY",
    acilim: "NAYY",
    tanim: "Alüminyum iletkenli PVC yalıtımlı güç kablosu ailesidir.",
    saha: "Güç dağıtımında kullanılır.",
    ilgili: "Kablo",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "THD",
    acilim: "Total Harmonic Distortion",
    tanim: "Toplam harmonik bozulma oranıdır.",
    saha: "Güç kalitesi analizinde kullanılır.",
    ilgili: "Kompanzasyon",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "Idyn",
    acilim: "Dinamik dayanım akımı",
    tanim:
        "Kısa devrenin elektromekanik etkilerine karşı dayanım değerlendirmesidir.",
    saha: "Bara ve şalt dayanımında önemlidir.",
    ilgili: "Pano",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "Icw",
    acilim: "Kısa süre dayanım akımı",
    tanim: "Ekipmanın belirli sürede dayanabildiği kısa devre akımıdır.",
    saha: "Pano doğrulamalarında kullanılır.",
    ilgili: "Pano",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "IP",
    acilim: "Ingress Protection",
    tanim: "Muhafazanın katı ve su girişine karşı koruma sınıfıdır.",
    saha: "Pano ve cihaz seçiminde kullanılır.",
    ilgili: "Pano",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "IK",
    acilim: "Mekanik darbe koruması",
    tanim: "Muhafazanın mekanik darbe dayanım sınıfıdır.",
    saha: "Dış ortam ekipmanlarında önemlidir.",
    ilgili: "Pano",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "ATS",
    acilim: "Automatic Transfer Switch",
    tanim: "Kaynaklar arasında otomatik transfer cihazıdır.",
    saha: "Şebeke ve jeneratör geçişinde kullanılır.",
    ilgili: "Jeneratör",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "Bara",
    acilim: "Busbar",
    tanim: "Elektrik dağıtımında kullanılan iletken sistemdir.",
    saha: "Panoda yüksek akım taşır.",
    ilgili: "Pano",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "Selektivite",
    acilim: "Koruma koordinasyonu",
    tanim: "Arızaya yakın korumanın önce açması prensibidir.",
    saha: "Enerji sürekliliğini artırır.",
    ilgili: "Koruma",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "Q-H",
    acilim: "Debi-basma yüksekliği eğrisi",
    tanim: "Pompanın debi ve basma yüksekliği performansını gösterir.",
    saha: "Pompa seçiminde gerçek çalışma noktasını doğrular.",
    ilgili: "GES Tarımsal",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "HMT",
    acilim: "Toplam basma yüksekliği",
    tanim: "Pompanın toplam basma yüksekliği ihtiyacıdır.",
    saha: "Pompa seçiminde debiyle birlikte kullanılır.",
    ilgili: "GES Tarımsal",
  ),
  EsaTeknikSozlukMaddesi(
    terim: "PWM",
    acilim: "Pulse Width Modulation",
    tanim: "Darbe genişlik modülasyonudur.",
    saha: "Güç elektroniği ve sürücülerde kullanılır.",
    ilgili: "Motor, GES",
  ),
];
